
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Locale;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import org.jdesktop.xswingx.PromptSupport;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wndessy
 */
public final class recordsForm extends javax.swing.JFrame {

    /**
     * Creates new form recordsForm
     */
    public recordsForm() {
        initComponents();

        PromptSupport.setPrompt("First Name", newStudentFirstName);
        PromptSupport.setPrompt("Middle Name", newStudentMiddleName);
        PromptSupport.setPrompt("Last Name", newStudentLastName);
        PromptSupport.setPrompt("Room number", newStudentRoomNumber);
        PromptSupport.setPrompt("ID Number", newStudentIdNumber);
        PromptSupport.setPrompt("Search", searchStudent);
        
        PromptSupport.setPrompt("First Name", EditNewStudentFirstName);
        PromptSupport.setPrompt("Middle Name", EditNewStudentMiddleName);
        PromptSupport.setPrompt("Last Name", EditNewStudentLastName);
        PromptSupport.setPrompt("Room number", EditNewStudentRoomNumber);
        PromptSupport.setPrompt("ID Number", EditNewStudentIdNumber);

        setUpAutoComplete();

    }

    public void setUpAutoComplete() {
        ArrayList<String> items = new ArrayList<>();
        Locale[] locales = Locale.getAvailableLocales();
        for (Locale locale : locales) {
            String item = locale.getDisplayName();
            items.add(item);
        }
        AutoComplete.setupAutoComplete(searchStudent, items);
        searchStudent.setColumns(20);
    }
    private final VarCommon vars = new VarCommon();
    private final DbModules db = new DbModules();
    private final homePage home = new homePage();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newStudentgender = new ButtonGroup();
        editStudentGender = new ButtonGroup();
        edittudentRecords = new JTabbedPane();
        RegisterStudent = new JPanel();
        textField3 = new TextField();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        btnBiodata = new JButton();
        btnSave = new JButton();
        male = new JRadioButton();
        female = new JRadioButton();
        reLogout = new JButton();
        clear = new JButton();
        back1 = new JButton();
        newStudentFirstName = new JTextField();
        newStudentIdNumber = new JTextField();
        newStudentLastName = new JTextField();
        newStudentMiddleName = new JTextField();
        newStudentRoomNumber = new JTextField();
        EditStudentDetails = new JPanel();
        searchStudent = new JTextField();
        male1 = new JRadioButton();
        male2 = new JRadioButton();
        jLabel3 = new JLabel();
        jButton3 = new JButton();
        jButton4 = new JButton();
        back = new JButton();
        editLogout = new JButton();
        clear1 = new JButton();
        jButton6 = new JButton();
        EditNewStudentFirstName = new JTextField();
        EditNewStudentMiddleName = new JTextField();
        EditNewStudentLastName = new JTextField();
        EditNewStudentRoomNumber = new JTextField();
        EditNewStudentIdNumber = new JTextField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        textField3.setText("textField1");

        jLabel2.setText("Gender");

        btnBiodata.setText("Bio Data");

        btnSave.setText("Save");
        btnSave.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        newStudentgender.add(male);
        male.setText("Male");

        newStudentgender.add(female);
        female.setText("Female");

        reLogout.setText("Logout");
        reLogout.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                reLogoutActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        back1.setText("Back");
        back1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        newStudentFirstName.setColumns(10);

        newStudentIdNumber.setColumns(10);

        newStudentLastName.setColumns(10);

        newStudentMiddleName.setColumns(10);

        newStudentRoomNumber.setColumns(10);

        GroupLayout RegisterStudentLayout = new GroupLayout(RegisterStudent);
        RegisterStudent.setLayout(RegisterStudentLayout);
        RegisterStudentLayout.setHorizontalGroup(
            RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(RegisterStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterStudentLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(male)
                            .addComponent(female))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(RegisterStudentLayout.createSequentialGroup()
                        .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(clear)
                            .addComponent(newStudentIdNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(newStudentFirstName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBiodata)
                            .addGroup(RegisterStudentLayout.createSequentialGroup()
                                .addComponent(newStudentMiddleName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newStudentLastName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(back1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(reLogout, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnSave))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(RegisterStudentLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterStudentLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(textField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterStudentLayout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newStudentRoomNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        RegisterStudentLayout.setVerticalGroup(
            RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(RegisterStudentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(newStudentIdNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(back1))
                .addGap(36, 36, 36)
                .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(newStudentFirstName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudentMiddleName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudentLastName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(reLogout))
                .addGap(16, 16, 16)
                .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterStudentLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textField3, GroupLayout.PREFERRED_SIZE, 0, GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterStudentLayout.createSequentialGroup()
                        .addComponent(male)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(female)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(newStudentRoomNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnBiodata)
                .addGap(18, 18, 18)
                .addGroup(RegisterStudentLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(clear))
                .addContainerGap())
        );

        edittudentRecords.addTab("Register student", RegisterStudent);

        searchStudent.setColumns(20);
        searchStudent.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                searchStudentActionPerformed(evt);
            }
        });

        editStudentGender.add(male1);
        male1.setText("Male");
        male1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                male1ActionPerformed(evt);
            }
        });

        editStudentGender.add(male2);
        male2.setText("Female");

        jLabel3.setText("Gender");

        jButton3.setText("Bio Data");

        jButton4.setText("Delete");

        back.setText("Back");
        back.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        editLogout.setText("Logout");
        editLogout.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                editLogoutActionPerformed(evt);
            }
        });

        clear1.setText("Clear");
        clear1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        jButton6.setText("Save");
        jButton6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        EditNewStudentFirstName.setColumns(10);

        EditNewStudentMiddleName.setColumns(10);

        EditNewStudentLastName.setColumns(10);

        EditNewStudentRoomNumber.setColumns(10);

        EditNewStudentIdNumber.setColumns(10);

        GroupLayout EditStudentDetailsLayout = new GroupLayout(EditStudentDetails);
        EditStudentDetails.setLayout(EditStudentDetailsLayout);
        EditStudentDetailsLayout.setHorizontalGroup(
            EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                        .addComponent(EditNewStudentIdNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchStudent, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(editLogout, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(back, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                        .addComponent(clear1)
                        .addGap(97, 97, 97)
                        .addComponent(jButton4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                        .addGroup(EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(male1)
                                    .addComponent(male2)))
                            .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                                .addComponent(EditNewStudentFirstName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditNewStudentMiddleName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditNewStudentLastName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                        .addComponent(EditNewStudentRoomNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        EditStudentDetailsLayout.setVerticalGroup(
            EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudent, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(back)
                    .addComponent(EditNewStudentIdNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(editLogout)
                .addGap(18, 18, 18)
                .addGroup(EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(EditNewStudentFirstName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditNewStudentMiddleName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditNewStudentLastName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(EditNewStudentRoomNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(EditStudentDetailsLayout.createSequentialGroup()
                        .addComponent(male1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(male2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(EditStudentDetailsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(clear1)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        edittudentRecords.addTab("Edit students records", EditStudentDetails);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(edittudentRecords)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edittudentRecords)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
        home.setVisible(true);

    }//GEN-LAST:event_backActionPerformed

    private void btnSaveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        vars.setFmane(newStudentFirstName.getText());
        vars.setMname(newStudentMiddleName.getText());
        vars.setLname(newStudentLastName.getText());
        vars.setId(newStudentIdNumber.getText());
        vars.setGender(getSelectedButtonText(newStudentgender));
        vars.setRoomNumber(newStudentRoomNumber.getText());
        vars.setBioData(btnBiodata.getText());
        System.out.print("" + vars.getFmane() + "  " + vars.getLname() + "  ");
        db.addUsser(vars);
        //admin.setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void reLogoutActionPerformed(ActionEvent evt) {//GEN-FIRST:event_reLogoutActionPerformed
        // TODO add your handling code here:
        LoginForm lg = new LoginForm();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reLogoutActionPerformed

    private void editLogoutActionPerformed(ActionEvent evt) {//GEN-FIRST:event_editLogoutActionPerformed
        // TODO add your handling code here:
        LoginForm lg = new LoginForm();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editLogoutActionPerformed

    private void male1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_male1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male1ActionPerformed

    private void clearActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void clear1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear1ActionPerformed

    private void jButton6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void back1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_back1ActionPerformed

    private void searchStudentActionPerformed(ActionEvent evt) {//GEN-FIRST:event_searchStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchStudentActionPerformed
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recordsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new recordsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField EditNewStudentFirstName;
    private JTextField EditNewStudentIdNumber;
    private JTextField EditNewStudentLastName;
    private JTextField EditNewStudentMiddleName;
    private JTextField EditNewStudentRoomNumber;
    private JPanel EditStudentDetails;
    private JPanel RegisterStudent;
    private JButton back;
    private JButton back1;
    private JButton btnBiodata;
    private JButton btnSave;
    private JButton clear;
    private JButton clear1;
    private JButton editLogout;
    private ButtonGroup editStudentGender;
    private JTabbedPane edittudentRecords;
    private JRadioButton female;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton6;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JRadioButton male;
    private JRadioButton male1;
    private JRadioButton male2;
    private JTextField newStudentFirstName;
    private JTextField newStudentIdNumber;
    private JTextField newStudentLastName;
    private JTextField newStudentMiddleName;
    private JTextField newStudentRoomNumber;
    private ButtonGroup newStudentgender;
    private JButton reLogout;
    private JTextField searchStudent;
    private TextField textField3;
    // End of variables declaration//GEN-END:variables
}
